# GENERAL NOTE the paths need to be ABSOLUTE!
env_path: "/media/ebonetto/WindowsData/Zebra_envs/Usable"
use_stl: False # this disable stl loading thus placement AND robot heading
use_npy: False
base_env_path: "/media/ebonetto/WindowsData/ov/isaac_sim-2022.2.1/GRADE-RR/usds/env_base.usd"
zebra_anims_loc: "/media/ebonetto/WindowsData/Zebra_anims"
randomize_sky: True # only if allowed
robot_mesh_path: "/media/ebonetto/WindowsData/ov/isaac_sim-2021.2.1/GRADE-RR/meshes/drone.dae"
usd_robot_path: "/media/ebonetto/WindowsData/ov/isaac_sim-2022.2.1/GRADE-RR/usds/drone_2022.usd"
out_folder: "/media/ebonetto/WindowsData/zebra_out_close"
out_folder_npy: "/media/ebonetto/WindowsData/zebra_out_close"
fps: 30
num_robots: 3
experiment_length: 220
anim_exp_len: 200
physics_hz: 240 # NOTE THAT THIS IS THE RATE OF CLOCK AND IMU
render_hz: 240 # LEAVE IT EQUAL TO PHYSICS HZ
npy_sensor_size: [1920, 1080]
env_prim_path: "/World/home"
robot_base_prim_path: "/my_robot_"
_recorder_settings: {
  "rgb": { "enabled": True },
  "depth": { "enabled": False, "colorize": False, "npy": True },
  "depthLinear": { "enabled": True, "colorize": False, "npy": True },
  "instance": { "enabled": True, "colorize": False, "npy": True, "mappings": True },
  "semantic": { "enabled": False, "colorize": False, "npy": True, "mappings": True },
  "bbox_2d_tight": { "enabled": True, "colorize": False, "npy": True },
  "bbox_2d_loose": { "enabled": True, "colorize": False, "npy": True },
  "normals": { "enabled": False, "colorize": False, "npy": True },
  "motion-vector": { "enabled": False, "colorize": True, "npy": True },
  "bbox_3d": { "enabled": True, "colorize": False, "npy": True },
  "camera": { "enabled": True, "colorize": True, "npy": True },
  "poses": { "enabled": True, "colorize": True, "npy": True },
}
min_number_zebras: 2
max_number_zebras: 5
